blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'



urlpatterns = [
# post views
path('post/', views.post_list, name='post_list'),
#path('', views.PostListView.as_view(), name='post_list'),
path('<int:year>/<int:month>/<int:day>/<slug:slug>/',views.post_detail,name='post_detail'),
path('<int:post_id>/share/',views.post_share, name='post_share'),
path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
path('feed/', LatestPostsFeed(), name='post_feed'),
path('search/', views.post_search, name='post_search'),



]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                    .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
    ('draft', 'Draft'),
    ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()


    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])
    class Meta:
        ordering = ('-publish',)
        
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'Comment by {self.body} on {self.name}'

blog/forms.py
from django import forms
from django.contrib.postgres.search import SearchVector




class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                                widget=forms.Textarea)
    

from .models import Comment, Post
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        
class SearchForm(forms.Form):
    query = forms.CharField()

def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.annotate(
                search=SearchVector('title', 'content'),
                                        ).filter(search=query)
    return render(request,
                'blog/post/search.html',
                {'form': form,
                'query': query,
                'results': results})

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchVector, SearchQuery,SearchRank, TrigramSimilarity

 

Post.objects.annotate(search=SearchVector('title', 'content'),).filter(search='django')



""" class PostListView(ListView):
    queryset = Post.published.all()
    
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'Blog/blog.html' """
    
 
def post_list(request, tag_slug=None, category_slug=None):
    
    ''' category = None
    
    productlist = Product.objects.all()
    categorylist = Category.objects.annotate(total_products=Count('product'))

    if category_slug :
        category = get_object_or_404(Category ,slug=category_slug)
        productlist = productlist.filter(category=category) '''
       
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 2) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
    # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    
    context = {'page': page,'posts': posts,'tag': tag, 'post_list': 'active'}   
    
    #context = {'page': page,'posts': posts,'tag': tag,'product_list' : productlist , 'category_list' : categorylist , 'count':Category.objects.count()}   
    
    return render(request,
                  'blog/blog.html',
                  context)
   
    
def post_detail(request,slug, year, month, day):
    post = get_object_or_404(Post, slug=slug,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
    # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
    # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
        # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
        
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                            .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                            .order_by('-same_tags','-publish')[:4]

    return render(request,
                  'blog/post_detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})
    

def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
        # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'breackeyawino@gmail.com',
                      [cd['to']])
            sent = True
        # ... send email
    else:
        form = EmailPostForm()
    return render(request, 
                  'blog/post_share.html', 
                  {'post': post,
                    'form': form,
                    'sent': sent})

def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'content')
            search_query = SearchQuery(query)
            results = Post.published.annotate(similarity=TrigramSimilarity('title', query),
                                                ).filter(similarity__gt=0.1).order_by('-similarity')
    return render(request,'blog/search.html',
                        {'form': form,
                        'query': query,
                        'results': results})
 

blog/templates/blog/blog.html
{% extends "users/layout.html" %}
{% load blog_tags %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Blog{% endblock %}

{% block content %}
<body id="bg">
<div class="page-wraper">

    <!-- Content -->
    <div class="page-content bg-white">
        <!-- inner page banner -->
        <div class="dez-bnr-inr overlay-black-middle" style="background-image:url(images/banner/bnr1.jpg);">
            <div class="container">
                <div class="dez-bnr-inr-entry">
                    <h1 class="text-white">Blog</h1>
					<!-- Breadcrumb row -->
					<div class="breadcrumb-row">
						<ul class="list-inline">
							<li><a href="#">Home</a></li>
							<li>Blog</li>
						</ul>
					</div>
					<!-- Breadcrumb row END -->
                </div>
            </div>
        </div>
        <!-- inner page banner END -->
        <div class="content-area">
            <div class="container">
                <div class="row">
                    <!-- Left part start -->
                    <div class="col-lg-8 col-md-7 col-sm-12">
                        <!-- Blog large img -->
						{% if tag %}
						<h2>Posts tagged with "{{ tag.name }}"</h2>
					{% endif %}

					   
					{% for post in posts %}   
						<div class="blog-post blog-lg blog-style-1">
							<div class="dez-info">
								 <div class="dez-post-meta">
									<ul class="d-flex align-items-center">
										<li class="post-date"><i class="fa fa-calendar"></i>{{ post.publish }}</li>
										<li class="post-author"><i class="fa fa-user"></i>By <a href="#">{{ post.author }}</a> </li>
										{% with comments.count as total_comments %}
										<li class="post-comment"><i class="fa fa-comments-o"></i><a href="#">
												{{ total_comments }} Comment{{ total_comments|pluralize }} </a></li>
										{% endwith %} 
									</ul>
								</div>
								<div class="dez-post-title ">
									<h4 class="post-title font-24"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
									<p class="tags">
										Tags:
										{% for tag in post.tags.all %}
										<a href="{% url 'blog:post_list_by_tag' tag.slug %}">
										{{ tag.name }}
										</a>
										{% if not forloop.last %}, {% endif %}
										{% endfor %}
										</p>
									
								</div>
								<div class="dez-post-text">
									<p>{{ post.content|markdown|truncatewords_html:30 }}</p>
								</div>
								<div class="dez-post-readmore blog-share"> 
									<a href="{{ post.get_absolute_url }}" title="READ MORE" rel="bookmark" class="site-button outline">READ MORE</a>
								</div>
							</div>
						</div>
						{% endfor %}

					 
						<!-- Blog large img END -->
                        <div class="pagination-bx clearfix text-center">

							<nav>
								{% if posts.has_other_pages %}
									<ul class="pagination justify-content-center">
										
										{% if posts.has_previous %}
											<li class="page-item"><a class="page-link active" href="?page={{ posts.previous_page_number }}">Prev</a></li>
										{% else %}
											<li class="disabled"></li>
										{% endif %}
							
										{% for pages in posts.paginator.page_range %}
											{% if posts.number == pages %}
												<li class="page-item"><a class="page-link" href="#">{{pages}}</a></li>
											{% else %}
												<li class="page-item"><a class="page-link active" href="?page={{ pages }}">{{pages}}</a></li>
											{% endif %}
										{% endfor %}
							
										{% if posts.has_next %}
											<li class="page-item"><a class="page-link active" href="?page={{ posts.next_page_number }}">Next</a></li>
										{% else %}
											<li class="disabled"></li>
										{% endif %}
										
									</ul>
								{% endif %}
							</nav>
 
						</div>
                        <!-- Pagination END -->
                    </div>
                    <!-- Left part END -->
                    <!-- Side bar start -->
                    <div class="col-lg-4 col-md-5 col-sm-12 sticky-top">
                        <aside  class="side-bar">
                            
							<div class="widget widget-popular-posts">
								<h4 class="widget-title">All posts ({% total_posts %})</h4>
                            <div class="widget recent-posts-entry">
                                <h6 class="widget-title style-1">Recent Posts</h6>
                                <div class="widget-post-bx">
                                    <div class="widget-post clearfix">
										{% show_latest_posts 3 %}
                                        <div class="dez-post-media"><a href="{{ post.get_absolute_url }}"> </div>
                                        <div class="dez-post-info">
                                            <div class="dez-post-header">
                                                <h6 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h6>
                                            </div>
										 
                                        </div>
                                    </div>
                                   
                                </div>
                            </div>
							
							<div class="widget">
								<h4 class="widget-title">Most commented posts</h4>
								{% get_most_commented_posts as most_commented_posts %}
							<ul class="posts-list">
								{% for post in most_commented_posts %}
							<li>
							<div class="widget-thumb">
							<a href="#"><img src="static/img/blog/thumb1.jpg" alt="" /></a>
							 </div>
							<div class="widget-content">
								<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
							<span><i class="icon-calendar"></i>{{ post.publish }}</span>
							</div>
							<div class="clearfix"></div>
							</li>
							{% endfor %}
 
							
						 
                        </aside>
                    </div>
                    <!-- Side bar END -->
                </div>
            </div>
        </div>
    </div>
    <!-- Content END-->
	<!-- Footer -->
    
{% endblock  %}

blog/templates/blog/latest_posts.html
<ul class="posts-list">
	{% for post in latest_posts %}
<li>

<div class="widget-content">
	<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
<span><i class="icon-calendar"></i>{{ post.publish }}</span>
</div>
<div class="clearfix"></div>
</li>
{% endfor %}
</ul>

blog/templates/blog/post_detail.html
{% extends "users/layout.html" %}
{% load blog_tags %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<body id="bg">
<div class="page-wraper">
 
    <!-- header END -->
    <!-- Content -->
    <div class="page-content bg-white">
        <!-- inner page banner -->
        <div class="dez-bnr-inr overlay-black-middle" style="background-image:url(images/banner/bnr1.jpg);">
            <div class="container">
                <div class="dez-bnr-inr-entry">
                    <h1 class="text-white">Blog Details</h1>
					<!-- Breadcrumb row -->
					<div class="breadcrumb-row">
						<ul class="list-inline">
							<li><a href="#">Home</a></li>
							<li>Blog Details</li>
						</ul>
					</div>
					<!-- Breadcrumb row END -->
                </div>
            </div>
        </div>
        <!-- inner page banner END -->
        <div class="content-area">
            <div class="container">
                <div class="row">
                    <!-- Left part start -->
                    <div class="col-lg-8 col-md-7 m-b10">
                        <!-- blog start -->
                        <div class="blog-post blog-single blog-style-1">
							<div class="dez-post-meta">
								<ul class="d-flex align-items-center">
									<li class="post-date"><i class="fa fa-calendar"></i>{{ post.publish }}</li>
									<li class="post-author"><i class="fa fa-user"></i>By <a href="#">{{ post.author }}</a> </li>
                                    {% with comments.count as total_comments %}
                                    <li class="post-comment"><i class="fa fa-comments-o"></i><a href="#">
                                            {{ total_comments }} Comment{{ total_comments|pluralize }} </a></li>
                                    {% endwith %} 
								</ul>
							</div>
                            <div class="dez-post-title">
                                <h4 class="post-title m-t0"><a href="#">{{ post.title }}</a></h4>
                            </div>
                            <div class="dez-post-media dez-img-effect zoom-slow m-t20"> <a href="#"><img src="static/images/blog/default/thum1.jpg" alt=""></a> </div>
                            <div class="dez-post-text">
                                {{ post.content|markdown }}
                            </div>
                            <div class="dez-post-tags clear">
                                <div class="post-tags">
                                    
                                    <p class="tags">
										Tags:
										{% for tag in post.tags.all %}
										<a href="{% url 'blog:post_list_by_tag' tag.slug %}">
										{{ tag.name }}
										</a>
										{% if not forloop.last %}, {% endif %}
										{% endfor %}
										</p>
                                    
                            </div>
							<div class="dez-divider bg-gray-dark op4"><i class="icon-dot c-square"></i></div>
							<div class="share-details-btn">
								<ul>
                                   
									<li><h5 class="m-a0">Share Post</h5></li>
									<li><a href="http://www.facebook.com/sharer/sharer.php?u=https://www.careers101.co.ke{{ request.get_full_path|urlencode }}" class="site-button facebook button-sm"><i class="fa fa-facebook"></i> Facebook</a></li>
									<li><a href="{% url 'blog:post_share' post.id %}" class="site-button google-plus button-sm"><i class="fa fa-google-plus"></i> Google Plus</a></li>
									<li><a href="http://www.linkedin.com/shareArticle?url=https://www.careers101.co.ke{{ request.get_full_path|urlencode }}&{{ post.title }}&summary={{ post.content}}&source=https://www.careers101.co.ke" class="site-button linkedin button-sm"><i class="fa fa-linkedin"></i> Linkedin</a></li>
									<li><a href="#" class="site-button instagram button-sm"><i class="fa fa-instagram"></i> Instagram</a></li>
									<li><a href="https://www.twitter.com/share?url=https://www.careers101.co.ke" class="site-button twitter button-sm"><i class="fa fa-twitter"></i> Twitter</a></li>
									<li><a href="#" class="site-button whatsapp button-sm"><i class="fa fa-whatsapp"></i> Whatsapp</a></li>
                                    
								</ul>
							</div>
                        </div>
                        <div class="clear" id="comment-list">
                            <div class="comments-area" id="comments">

                                {% with comments.count as total_comments %}
                                <h2 class="comments-title">{{ total_comments }} Comment{{ total_comments|pluralize }}</h2>
                                    {% endwith %}
                                       
                                <div class="clearfix m-b20">
                                    <!-- comment list END -->
                                    <ol class="comment-list">
                                        {% for comment in comments %}
                                        <li class="comment">
                                            <div class="comment-body">
                                                <div class="comment-author vcard"> <img  class="avatar photo" src="{% static 'images/blog/blog-user.png' %}" alt=""> <cite class="fn">Comment {{ forloop.counter }} by {{ comment.name }}</h4></cite> <span class="says">says:</span> </div>
                                                <div class="comment-meta"> <a href="#">{{ comment.created }}</a> </div>
                                                <p>{{ comment.body|linebreaks }}</p>
                                                <div class="reply"> <a href="#" class="comment-reply-link">Reply</a> </div>
                                            </div>
                                            {% comment %} <ol class="children">
                                                <li class="comment odd parent">
                                                    <div class="comment-body">
                                                        <div class="comment-author vcard"> <img  class="avatar photo" src="images/testimonials/pic2.jpg" alt=""> <cite class="fn">Comment {{ forloop.counter }} by {{ comment.name }}</cite> <span class="says">says:</span> </div>
                                                        <div class="comment-meta"> <a href="#">{{ comment.created }}</a> </div>
                                                        <p>{{ comment.body|linebreaks }}</p>
                                                        <div class="reply"> <a href="#" class="comment-reply-link">Reply</a> </div>
                                                    </div>
                                                    <!-- list END -->
                                                </li>
                                            </ol>
                                            <!-- list END --> {% endcomment %}
                                        </li>
                                        {% empty %}
                                        <p>There are no comments yet.</p>
                                        {% endfor %}
                                    </ol>
                                    <!-- comment list END -->
                                    <!-- Form -->
                                </div>
                                    <div id="respond">
                                        {% if new_comment %} 
                                        <div class="alert alert-success" role="alert">
                                            Your comment is awaiting moderation
                                        </div>                                    
                                  
                                    </div>
                                   
                                    {% else %}

                                    <div class="comment-respond" id="respond">
                                        <h4 class="comment-reply-title" id="reply-title">Leave a Comment <small> <a style="display:none;" href="#" id="cancel-comment-reply-link" rel="nofollow">Cancel reply</a> </small> </h4>
                                        <form class="comment-form" id="commentform" method="post">
                                            <div class="form-group">
                                                {% csrf_token %}
                                                {% bootstrap_form comment_form %}
                                                {% buttons %}
                                                    <button class="btn btn-common log-btn" type="submit">Post Comment</button>
                                                {% endbuttons %}
                                            
                                                {% endif %}
                                            </div>
                                        </form>
                                    </div>
                                    <!-- Form -->
                            </div>
                        </div>
                        <!-- blog END -->
                    </div>
                </div>
            </div>
                    <!-- Left part END -->
                    <!-- Side bar start -->
                    <div class="col-lg-4 col-md-5 sticky-top">
                        <aside  class="side-bar">
                            <div class="widget  recent-posts-entry">
                                <h4 class="widget-title">Similar posts</h4>
                                <ul class="posts-list">
                                    {% for post in similar_posts %}
                                <li>
                                <div class="widget-content">
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                <span><i class="icon-calendar"></i>{{ post.publish }}</span>
                                </div>
                                <div class="clearfix"></div>
                                </li>
                                {% empty %}
                                    There are no similar posts yet.
                                {% endfor %}
                                </ul>
                            </div>


                            <div class="widget recent-posts-entry">
                                <h6 class="widget-title">Recent Posts</h6>
                                <div class="widget-post-bx">
                                    <div class="widget-post clearfix">
										{% show_latest_posts 3 %}
                                        {% comment %} <div class="dez-post-info">
                                            <div class="dez-post-header">
                                                <h6 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h6>
                                            </div>
											 
                                        </div> {% endcomment %}
                                    </div>

                                    <div class="widget recent-posts-entry">
                                        <h4 class="widget-title">Most commented posts</h4>
                                        {% get_most_commented_posts as most_commented_posts %}
                                    <ul class="posts-list">
                                        {% for post in most_commented_posts %}
                                    <li>
                                    
                                    <div class="widget-content">
                                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                    <span><i class="icon-calendar"></i>{{ post.publish }}</span>
                                    </div>
                                    <div class="clearfix"></div>
                                    </li>
                                    {% endfor %}
                                </ul>
                                  
                                </div>
                            </div>
					 
						 
							 
                        </aside>
                    </div>
                    <!-- Side bar END -->
                </div>
            </div>
        </div>
    </div>
    <!-- Content END-->
	<!-- Footer -->
    {% endblock  %}

blog/templates/blog/post_share.html
{% extends "users/layout.html" %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Share a post{% endblock %}
{% block content %}

<div class="page-header" style="background: url(static/img/banner1.jpg);">
    <div class="container">
    <div class="row">
    <div class="col-md-12">
    <div class="breadcrumb-wrapper">
    <h2 class="product-title">Blog</h2>
    <ol class="breadcrumb">
    <li><a href="#">Home /</a></li>
    <li class="current">Share Post</li>
    </ol>
    </div>
    </div>
    </div>
    </div>
    </div>
    
    
    <div id="content" class="section-padding">
    <div class="container">
    <div class="row">
    <div class="col-lg-8 col-md-12 col-xs-12">   
        {% if sent %}
        <h2>E-mail successfully sent</h2>
        <h3>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</h3>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %} 
            {% buttons %}
                <button class="btn btn-common log-btn" type="submit">Send E-mail</button>
            {% endbuttons %}

           <!--  iterate trough all fields
            {% for field in form %}
                <div>
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %} -->
        </form>
    {% endif %}

    
    </div>
    </div>
    </div>


     
{% endblock %}

blog/templates/blog/search.html
{% extends "users/layout.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}

<body id="bg">
<div class="page-wraper">
 
    <!-- header END -->
    <!-- Content -->
    <div class="page-content bg-white">
        <!-- inner page banner -->
        <div class="dez-bnr-inr overlay-black-middle" style="background-image:url(images/banner/bnr1.jpg);">
            <div class="container">
                <div class="dez-bnr-inr-entry">
                    <h1 class="text-white">Blog Details</h1>
					<!-- Breadcrumb row -->
					<div class="breadcrumb-row">
						<ul class="list-inline">
							<li><a href="#">Home</a></li>
							<li>Search Results</li>
						</ul>
					</div>
					<!-- Breadcrumb row END -->
    </div>
    </div></div>
    
    <div id="content" class="section-padding">
    <div class="container">
    <div class="row">
    <div class="col-lg-8 col-md-12 col-xs-12">
    
    <div class="blog-post single-post">
    
        
    {% if query %}
    <h1>Posts containing "{{ query }}"</h1> 
    <div class="hover-wrap">
    </div>
    </div>
    <h3>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
        </h3>
        {% for post in results %}
    <div class="post-content">
    <h2 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
   
    <div class="entry-summary">
        {{ post.content|markdown|truncatewords_html:5 }}
        {% empty %}
        <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}"><u><b>Search again</b></u></a></p>
        {% else %}
        <br/>
        <h4 class="widget-title">Search for posts</h4>
        <form method="get">
        {{ form|crispy }}
        <input type="submit" class="site-button" value="Search">
        </form>
        {% endif %}
                 
    </div>
    </div>
    
    </div>
 

{% endblock %}